import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { CapacitorBarcodeScanner, CapacitorBarcodeScannerTypeHint } from "@capacitor/barcode-scanner";
import { Capacitor } from "@capacitor/core";
import { PushNotifications } from "@capacitor/push-notifications";
import "./style.css";

const API = "https://meaningful-plushies-fulfilment.vercel.app/api/mobile";
const SESSION_KEY = "meaningful-fulfilment-mobile-session-v1";
const DASHBOARD_KEY = "meaningful-fulfilment-mobile-dashboard-v3";
const REPORT_KEY = "meaningful-fulfilment-mobile-report-v1";
const PAGE_SIZE = 100;
const CACHE_MAX_AGE = 5 * 60 * 1000;
const UPDATE_URL = "https://github.com/IvanPJH05/meaningful-plushies-fulfilment/releases/latest/download/app-debug.apk";
const money = new Intl.NumberFormat("en-MY", { style: "currency", currency: "MYR", maximumFractionDigits: 2 });

type Session = { token: string; username: string; displayName: string; role: "admin" | "staff" };
type Order = { id: string; orderNumber: string; orderDate: string; customerName: string; phone: string; address: string; plushName: string; status: string; character: string; product: string; voiceLength: number; paymentProcessor: string; totalAmount: number; courier: string; trackingNumber: string };
type OrderDetails = { email: string; subtotalAmount: number; shippingAmount: number; discountAmount: number; outstandingBalance: number; meaningfulNote: string; plushGender?: string; plushBirthDate?: string; plushBelongsTo?: string; voice: { url: string; fileName: string } | null };
type Detail = { order: Order; details: OrderDetails };
type Dashboard = { counts: Record<string, number>; orders: Order[]; totalCount: number; hasMore: boolean; latestUpdatedAt: string | null; savedAt: number };
type ManualOrder = { id: string; customerName: string; customerEmail: string; phoneOriginal: string; character: string; productDisplayName: string; customisationSessionId: string; speakerSeconds?: number; amountToCollect?: number | null; shippingRegion?: "WEST" | "EAST"; shippingAddress: { address1: string; address2?: string; city: string; province: string; zip: string }; paymentReceipts: Array<{ fileName: string; url: string }>; isCod: boolean; status: "awaiting_payment" | "ready_to_create" | "created" | "cancelled"; shopifyOrderName: string; createdAt: string; paymentApprovedAt: string };
type ManualDetail = { intake: ManualOrder; form: { plushName?: string; gender?: string; birthDate?: string; belongsTo?: string; meaningfulNote?: string } | null; voiceUrl: string; voiceFileName: string };
type Workspace = "fulfilment" | "manual_orders" | "reports" | "updates";
type SourceFilter = "all" | "shopify" | "tiktok";
type SalesReport = { sales: { gross: number; totalCollected: number; productDiscounted: number; shippingDiscounted: number; totalFees: number; collected: number }; channel: { shopify: { count: number; sales: number }; tiktok: { count: number; sales: number } }; orderCount: number; savedAt?: number };

const labels: Record<string, string> = { awaiting_customisation: "Awaiting customisation", new_order: "New order", uploading_audio: "Uploading audio", sent_for_sewing: "Sent for sewing", packed: "Packed", shipped: "Shipped", issue: "Issue" };
const next: Record<string, string> = { awaiting_customisation: "new_order", new_order: "uploading_audio", uploading_audio: "sent_for_sewing", sent_for_sewing: "packed", packed: "shipped" };
function stored<T>(key: string, fallback: T): T { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }
function save(key: string, value: unknown) { try { localStorage.setItem(key, JSON.stringify(value)); } catch { /* cache is optional */ } }
function date(value: string) { return value ? new Date(value).toLocaleDateString("en-MY", { day: "numeric", month: "short", year: "numeric" }) : "—"; }
function manualStatus(order: ManualOrder) { if (order.status === "created") return order.isCod ? "COD" : "Paid"; if (order.status === "ready_to_create") return order.isCod ? "COD approved" : "Receipt attached"; return "Awaiting payment"; }
function manualAddress(order: ManualOrder) { const a = order.shippingAddress; return [a.address1, a.address2, a.city, a.province, a.zip].filter(Boolean).join(", "); }

function App() {
  const [session, setSession] = useState<Session | null>(() => stored<Session | null>(SESSION_KEY, null));
  const [username, setUsername] = useState(""); const [password, setPassword] = useState("");
  const [dashboard, setDashboard] = useState<Dashboard>(() => stored<Dashboard>(DASHBOARD_KEY, { counts: {}, orders: [], totalCount: 0, hasMore: false, latestUpdatedAt: null, savedAt: 0 }));
  const [selected, setSelected] = useState<Detail | null>(null); const [manualDetail, setManualDetail] = useState<ManualDetail | null>(null);
  const [workspace, setWorkspace] = useState<Workspace>("fulfilment"); const [workspaceOpen, setWorkspaceOpen] = useState(false);
  const [manualOrders, setManualOrders] = useState<ManualOrder[]>([]); const [manualHistory, setManualHistory] = useState<ManualOrder[]>([]); const [manualPage, setManualPage] = useState<"approvals" | "history">("approvals");
  const [statusFilter, setStatusFilter] = useState("all"); const [sourceFilter, setSourceFilter] = useState<SourceFilter>("all"); const [fromDate, setFromDate] = useState(""); const [toDate, setToDate] = useState(""); const [salesReport, setSalesReport] = useState<SalesReport | null>(() => stored<SalesReport | null>(REPORT_KEY, null)); const [reportLoading, setReportLoading] = useState(false);
  const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [loadingMore, setLoadingMore] = useState(false); const [opening, setOpening] = useState(false);
  const [updatesAvailable, setUpdatesAvailable] = useState(false); const [pullDistance, setPullDistance] = useState(0);

  function orderFilters() { const params = new URLSearchParams({ pageSize: String(PAGE_SIZE), status: statusFilter, source: sourceFilter }); if (fromDate) params.set("from", fromDate); if (toDate) params.set("to", toDate); return params; }
  async function fetchPage(page: number, replace = false) {
    if (!session) return;
    const params = orderFilters(); params.set("page", String(page));
    const response = await fetch(`${API}/dashboard?${params}`, { cache: "no-store", headers: { authorization: `Bearer ${session.token}` } });
    const data = await response.json(); if (!response.ok) throw new Error(data.error);
    const fresh: Dashboard = { counts: data.counts || {}, orders: replace ? data.orders || [] : [...dashboard.orders, ...(data.orders || [])], totalCount: data.totalCount || 0, hasMore: data.hasMore === true, latestUpdatedAt: data.latestUpdatedAt || null, savedAt: Date.now() };
    setDashboard(fresh); save(DASHBOARD_KEY, fresh); setUpdatesAvailable(false); setNotice("");
  }
  async function refresh(force = false) { if (!session || (!force && dashboard.savedAt && Date.now() - dashboard.savedAt < CACHE_MAX_AGE)) return; setBusy(true); try { await fetchPage(0, true); } catch (error) { const message = error instanceof Error ? error.message : "Could not load orders."; if (message.includes("REQUIRED")) { localStorage.removeItem(SESSION_KEY); setSession(null); } else setNotice(message); } finally { setBusy(false); } }
  async function checkForUpdates() {
    if (!session || document.visibilityState !== "visible") return;
    try {
      const response = await fetch(`${API}/dashboard?check=1`, { cache: "no-store", headers: { authorization: `Bearer ${session.token}` } });
      const data = await response.json();
      if (!response.ok) return;
      if ((dashboard.latestUpdatedAt && data.latestUpdatedAt && data.latestUpdatedAt !== dashboard.latestUpdatedAt) || Number(data.totalCount || 0) > dashboard.totalCount) setUpdatesAvailable(true);
    } catch { /* Existing saved orders remain available when temporarily offline. */ }
  }
  useEffect(() => {
    void refresh();
    void checkForUpdates();
    const interval = window.setInterval(() => void checkForUpdates(), 30000);
    const onVisible = () => { if (document.visibilityState === "visible") void checkForUpdates(); };
    document.addEventListener("visibilitychange", onVisible);
    return () => { window.clearInterval(interval); document.removeEventListener("visibilitychange", onVisible); };
  }, [session?.token, dashboard.latestUpdatedAt, dashboard.totalCount]);
  useEffect(() => { if (!session) return; if (workspace === "reports") { void loadSalesReport(); return; } void refresh(true); }, [session?.token, workspace, statusFilter, sourceFilter, fromDate, toDate]);
  useEffect(() => {
    let startY = 0;
    const start = (event: TouchEvent) => { if (window.scrollY <= 0 && !busy) startY = event.touches[0]?.clientY || 0; };
    const move = (event: TouchEvent) => { if (!startY || window.scrollY > 0) return; setPullDistance(Math.min(90, Math.max(0, (event.touches[0]?.clientY || 0) - startY))); };
    const end = () => { const shouldRefresh = pullDistance >= 56; startY = 0; setPullDistance(0); if (shouldRefresh) void refresh(true); };
    window.addEventListener("touchstart", start, { passive: true });
    window.addEventListener("touchmove", move, { passive: true });
    window.addEventListener("touchend", end, { passive: true });
    return () => { window.removeEventListener("touchstart", start); window.removeEventListener("touchmove", move); window.removeEventListener("touchend", end); };
  }, [busy, pullDistance, session?.token]);
  useEffect(() => {
    if (!session || Capacitor.getPlatform() === "web") return;
    const activeSession = session;
    let cancelled = false;
    let registrationListener: Awaited<ReturnType<typeof PushNotifications.addListener>> | undefined;
    let receivedListener: Awaited<ReturnType<typeof PushNotifications.addListener>> | undefined;
    let actionListener: Awaited<ReturnType<typeof PushNotifications.addListener>> | undefined;

    async function registerDevice(token: string) {
      const response = await fetch(`${API}/notifications/register`, {
        method: "POST",
        headers: { "content-type": "application/json", authorization: `Bearer ${activeSession.token}` },
        body: JSON.stringify({ token, platform: Capacitor.getPlatform() }),
      });
      if (!response.ok) throw new Error("Could not enable notifications on this device.");
    }

    async function setUpNotifications() {
      try {
        registrationListener = await PushNotifications.addListener("registration", (token) => {
          if (!cancelled) void registerDevice(token.value).catch(() => setNotice("Notifications could not be enabled. Try reopening the app."));
        });
        receivedListener = await PushNotifications.addListener("pushNotificationReceived", (notification) => {
          if (!cancelled) setNotice(notification.body || notification.title || "A new Manual Order was received.");
        });
        actionListener = await PushNotifications.addListener("pushNotificationActionPerformed", () => {
          if (cancelled) return;
          setWorkspace("manual_orders");
          void loadManualApprovals();
        });
        const permission = await PushNotifications.checkPermissions();
        const result = permission.receive === "prompt" ? await PushNotifications.requestPermissions() : permission;
        if (result.receive === "granted") await PushNotifications.register();
      } catch {
        if (!cancelled) setNotice("Notifications are unavailable on this device.");
      }
    }

    void setUpNotifications();
    return () => {
      cancelled = true;
      registrationListener?.remove();
      receivedListener?.remove();
      actionListener?.remove();
    };
  }, [session?.token]);
  async function login(event: React.FormEvent) { event.preventDefault(); setBusy(true); try { const response = await fetch(`${API}/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username, password }) }); const data = await response.json(); if (!response.ok) throw Error(data.error); setSession(data); save(SESSION_KEY, data); setPassword(""); setNotice(""); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to sign in."); } finally { setBusy(false); } }
  async function loadMore() { if (!session || loadingMore || !dashboard.hasMore) return; setLoadingMore(true); try { await fetchPage(Math.floor(dashboard.orders.length / PAGE_SIZE), false); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not load more orders."); } finally { setLoadingMore(false); } }
  async function openOrder(id: string) { if (!session) return; setOpening(true); setNotice(""); try { const response = await fetch(`${API}/orders/${id}`, { headers: { authorization: `Bearer ${session.token}` } }); const data = await response.json(); if (!response.ok) throw Error(data.error); setSelected(data); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not open this order."); } finally { setOpening(false); } }
  async function lookup(code: string) { if (!session || !code) return; setBusy(true); try { const response = await fetch(`${API}/orders/lookup?code=${encodeURIComponent(code)}`, { headers: { authorization: `Bearer ${session.token}` } }); const data = await response.json(); if (!response.ok) throw Error(data.error); if (!data.order) throw Error("No order matches this code."); await openOrder(data.order.id); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not find this order."); } finally { setBusy(false); } }
  async function scan() { try { const result = await CapacitorBarcodeScanner.scanBarcode({ hint: CapacitorBarcodeScannerTypeHint.ALL, scanInstructions: "Scan the order barcode or QR code" }); if (result.ScanResult) await lookup(result.ScanResult); } catch { setNotice("The camera scanner could not start. You can enter the code manually."); } }
  async function advance() { if (!session || !selected || !next[selected.order.status]) return; setBusy(true); try { const response = await fetch(`${API}/orders/transition`, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${session.token}` }, body: JSON.stringify({ orderId: selected.order.id, fromStatus: selected.order.status, toStatus: next[selected.order.status] }) }); const data = await response.json(); if (!response.ok) throw Error(data.error === "ORDER_CHANGED" ? "This order changed on another device. Open it again." : data.error); setSelected({ ...selected, order: data.order }); const fresh = { ...dashboard, orders: dashboard.orders.map((item) => item.id === data.order.id ? data.order : item), savedAt: Date.now() }; setDashboard(fresh); save(DASHBOARD_KEY, fresh); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not update this order."); } finally { setBusy(false); } }
  async function loadManualOrders() { if (!session) return; setBusy(true); try { const response = await fetch(`${API}/manual-orders`, { headers: { authorization: `Bearer ${session.token}` } }); const data = await response.json(); if (!response.ok) throw Error(data.error); setManualOrders(data.intakes || []); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not load Manual Orders."); } finally { setBusy(false); } }
  async function loadManualApprovals() { if (!session) return; setBusy(true); try { const response = await fetch(`${API}/manual-orders?scope=awaiting`, { cache: "no-store", headers: { authorization: `Bearer ${session.token}` } }); const data = await response.json(); if (!response.ok) throw Error(data.error); setManualOrders(data.intakes || []); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not load Manual Orders."); } finally { setBusy(false); } }
  async function loadManualHistory() { if (!session) return; setBusy(true); try { const response = await fetch(`${API}/manual-orders?scope=history`, { cache: "no-store", headers: { authorization: `Bearer ${session.token}` } }); const data = await response.json(); if (!response.ok) throw Error(data.error); setManualHistory(data.intakes || []); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not load transaction history."); } finally { setBusy(false); } }
  async function loadSalesReport() { if (!session || session.role !== "admin") return; setReportLoading(true); try { const params = new URLSearchParams({ source: sourceFilter }); if (fromDate) params.set("from", fromDate); if (toDate) params.set("to", toDate); const response = await fetch(`${API}/reports?${params}`, { cache: "no-store", headers: { authorization: `Bearer ${session.token}` } }); const data = await response.json(); if (!response.ok) throw Error(data.error); const fresh = { ...data, savedAt: Date.now() }; setSalesReport(fresh); save(REPORT_KEY, fresh); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not load sales reporting."); } finally { setReportLoading(false); } }
  async function openManualOrder(id: string) { if (!session) return; setOpening(true); try { const response = await fetch(`${API}/manual-orders`, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${session.token}` }, body: JSON.stringify({ action: "details", id }) }); const data = await response.json(); if (!response.ok) throw Error(data.error); setManualDetail(data.details); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not open this Manual Order."); } finally { setOpening(false); } }
  async function chooseWorkspace(item: Workspace) { setWorkspace(item); setWorkspaceOpen(false); setNotice(""); if (item === "manual_orders") { setManualPage("approvals"); await loadManualApprovals(); } if (item === "fulfilment") await refresh(true); }
  function signOut() { localStorage.removeItem(SESSION_KEY); setSession(null); }
  const name = workspace === "fulfilment" ? "Fulfilment" : workspace === "manual_orders" ? "Manual Orders" : workspace === "reports" ? "Reports" : "Updates";
  if (opening && workspace === "manual_orders") return <main aria-live="polite" style={{ display: "grid", minHeight: "100vh", placeItems: "center", background: "linear-gradient(145deg, #f1faf7, #f6f6f7)", textAlign: "center" }}><div style={{ display: "grid", justifyItems: "center", gap: 14, maxWidth: 330, padding: "30px 24px", background: "#fff", border: "1px solid #d9ebe5", borderRadius: 16, boxShadow: "0 12px 32px #00806016" }}><svg aria-hidden="true" width="46" height="46" viewBox="0 0 46 46"><circle cx="23" cy="23" r="18" fill="none" stroke="#d9f2ed" strokeWidth="5" /><path d="M23 5a18 18 0 0 1 18 18" fill="none" stroke="#008060" strokeWidth="5" strokeLinecap="round"><animateTransform attributeName="transform" type="rotate" from="0 23 23" to="360 23 23" dur="0.8s" repeatCount="indefinite" /></path></svg><h1 style={{ fontSize: 23 }}>Opening order</h1><p>Loading the customer details, customisation, voice message, and payment information.</p></div></main>;
  const picker = <div className="workspace-control"><button className="workspace-trigger" onClick={() => setWorkspaceOpen((open) => !open)} aria-expanded={workspaceOpen}><span>{name}</span><b>⌄</b></button>{workspaceOpen && <div className="workspace-menu"><button className={workspace === "fulfilment" ? "active" : ""} onClick={() => void chooseWorkspace("fulfilment")}><strong>Fulfilment</strong><small>Orders and production</small></button>{session?.role === "admin" && <><button className={workspace === "manual_orders" ? "active" : ""} onClick={() => void chooseWorkspace("manual_orders")}><strong>Manual Orders</strong><small>Payment approvals</small></button><button className={workspace === "reports" ? "active" : ""} onClick={() => void chooseWorkspace("reports")}><strong>Reports</strong><small>Sales and cash collected</small></button></>}<button className={workspace === "updates" ? "active" : ""} onClick={() => void chooseWorkspace("updates")}><strong>Updates</strong><small>Install the latest app</small></button></div>}</div>;

  if (!session) return <main className="login"><span className="shopify-mark">MP</span><h1>Meaningful Fulfilment</h1><p>Sign in to your warehouse workspace.</p><form onSubmit={login}><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" /></label><label>Password<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete="current-password" /></label><button disabled={busy}>{busy ? "Signing in…" : "Sign in"}</button></form>{notice && <p className="error">{notice}</p>}</main>;
  if (selected) return <main><header className="topbar"><div>{picker}<button className="back" onClick={() => setSelected(null)}>‹ Back to orders</button></div><span className="shopify-mark">MP</span></header><div className="detail-title"><div><span className="eyebrow">ORDER</span><h1>#{selected.order.orderNumber}</h1><span className={`status status-${selected.order.status}`}>{labels[selected.order.status] || selected.order.status}</span></div><button className="quiet" onClick={() => void refresh(true)}>Refresh</button></div><section className="card"><h2>{selected.order.plushName || selected.order.product || "Meaningful Plushie"}</h2><p>{selected.order.character || "Character not set"} · {selected.order.voiceLength || 0} seconds</p>{selected.details.voice ? <div className="voice-card"><strong>Voice message</strong><small>{selected.details.voice.fileName}</small><audio controls preload="metadata" src={selected.details.voice.url} /></div> : <p className="muted">No playable voice message is available.</p>}</section><section className="card"><h2>Payment</h2><div className="detail-grid"><div><span>Total paid</span><strong>{money.format(selected.order.totalAmount || 0)}</strong></div><div><span>Method</span><strong>{selected.order.paymentProcessor || "—"}</strong></div><div><span>Subtotal</span><strong>{money.format(selected.details.subtotalAmount || 0)}</strong></div><div><span>Shipping</span><strong>{money.format(selected.details.shippingAmount || 0)}</strong></div><div><span>Discount</span><strong>{money.format(selected.details.discountAmount || 0)}</strong></div><div><span>Outstanding</span><strong>{money.format(selected.details.outstandingBalance || 0)}</strong></div></div></section><section className="card"><h2>Customer</h2><p><strong>{selected.order.customerName || "—"}</strong><br />{selected.order.phone || "No phone"}<br />{selected.details.email || "No email"}</p><p>{selected.order.address || "No delivery address"}</p></section><section className="card"><h2>Plushie details</h2><div className="detail-grid"><div><span>Name</span><strong>{selected.order.plushName || "—"}</strong></div><div><span>Gender</span><strong>{selected.details.plushGender || "—"}</strong></div><div><span>Born on</span><strong>{selected.details.plushBirthDate || "—"}</strong></div><div><span>Belongs to</span><strong>{selected.details.plushBelongsTo || "—"}</strong></div></div>{selected.details.meaningfulNote && <p className="note">{selected.details.meaningfulNote}</p>}</section><section className="card"><h2>Delivery</h2><div className="detail-grid"><div><span>Courier</span><strong>{selected.order.courier || "—"}</strong></div><div><span>Tracking</span><strong>{selected.order.trackingNumber || "—"}</strong></div></div></section>{next[selected.order.status] && <button className="primary-action" disabled={busy} onClick={() => void advance()}>{busy ? "Updating…" : `Move to ${labels[next[selected.order.status]]}`}</button>}{notice && <p className="error">{notice}</p>}</main>;
  if (manualDetail) return <main><header className="topbar"><div>{picker}<button className="back" onClick={() => setManualDetail(null)}>‹ Back to Manual Orders</button></div><span className="shopify-mark">MP</span></header><div className="detail-title"><div><span className="eyebrow">MANUAL ORDER</span><h1>{manualDetail.intake.customerName || "Customer"}</h1><p>{manualStatus(manualDetail.intake)}</p></div></div><section className="card"><h2>Order</h2><p><strong>{manualDetail.intake.character} · {manualDetail.intake.productDisplayName}</strong><br />Submitted {date(manualDetail.intake.createdAt)}<br />{manualDetail.intake.shopifyOrderName || "Not created in Shopify yet"}</p></section><section className="card"><h2>Customer and delivery</h2><p><strong>{manualDetail.intake.customerName}</strong><br />{manualDetail.intake.phoneOriginal}<br />{manualDetail.intake.customerEmail}</p><p>{manualAddress(manualDetail.intake)}</p></section><section className="card"><h2>Customisation</h2><div className="detail-grid"><div><span>Plush name</span><strong>{manualDetail.form?.plushName || "—"}</strong></div><div><span>Gender</span><strong>{manualDetail.form?.gender || "—"}</strong></div><div><span>Born on</span><strong>{manualDetail.form?.birthDate || "—"}</strong></div><div><span>Belongs to</span><strong>{manualDetail.form?.belongsTo || "—"}</strong></div></div>{manualDetail.form?.meaningfulNote && <p className="note">{manualDetail.form.meaningfulNote}</p>}{manualDetail.voiceUrl && <div className="voice-card"><strong>Voice message</strong><small>{manualDetail.voiceFileName || "Voice message"}</small><audio controls src={manualDetail.voiceUrl} /></div>}</section><section className="card"><h2>Payment</h2><p><strong>{manualStatus(manualDetail.intake)}</strong><br />{manualDetail.intake.paymentApprovedAt ? `Approved ${date(manualDetail.intake.paymentApprovedAt)}` : "No receipt approved yet"}</p>{manualDetail.intake.paymentReceipts.filter((receipt) => !receipt.url.startsWith("manual-order:")).map((receipt) => <a className="receipt-link" key={receipt.url} href={receipt.url} target="_blank" rel="noreferrer">Open receipt: {receipt.fileName || "Receipt"}</a>)}</section>{notice && <p className="error">{notice}</p>}</main>;
  if (workspace === "updates") return <main><header className="topbar"><div>{picker}<p className="eyebrow">MOBILE APP</p><h1>Updates</h1></div><button className="avatar" onClick={signOut}>{session.displayName.slice(0, 1).toUpperCase()}</button></header><section className="card update-card"><span className="update-dot" /><div><h2>Latest mobile app</h2><p>Download the newest version when an update is available.</p></div><a className="update-button" href={UPDATE_URL}>Download and install update</a><small>Android will ask you to confirm installation. Your saved sign-in and order cache stay on your phone.</small></section></main>;
  if (workspace === "manual_orders") return <main><header className="topbar"><div>{picker}<p className="eyebrow">MANUAL ORDERS</p><h1>{manualPage === "approvals" ? "Payment approvals" : "Transaction history"}</h1><p>{manualPage === "approvals" ? `${manualOrders.length} awaiting approval` : `${manualHistory.length} completed records`}</p></div><button className="avatar" onClick={signOut}>{session.displayName.slice(0, 1).toUpperCase()}</button></header><div className="workspace-tabs"><button className={manualPage === "approvals" ? "active" : ""} onClick={() => { setManualPage("approvals"); void loadManualApprovals(); }}>Awaiting approval</button><button className={manualPage === "history" ? "active" : ""} onClick={() => { setManualPage("history"); void loadManualHistory(); }}>Transaction history</button></div>{manualPage === "approvals" ? <section className="order-list"><div className="list-heading"><h2>Awaiting approval</h2><span>{manualOrders.length}</span></div>{manualOrders.map((order) => <button className="order-row manual-approval-row" key={order.id} onClick={() => void openManualOrder(order.id)}><div><strong>{order.customerName || "Customer"}</strong><span>{order.character} · {order.speakerSeconds || 0} seconds · {order.shippingRegion === "EAST" ? "East Malaysia" : "West Malaysia"}</span><small>{order.phoneOriginal}</small><small>Customisation ID: {order.customisationSessionId || "—"}</small><small className="collect">To collect: {order.amountToCollect === null || order.amountToCollect === undefined ? "Price unavailable" : money.format(order.amountToCollect)}</small></div><div><span className="status status-awaiting_customisation">Awaiting payment</span><b>›</b></div></button>)}{!manualOrders.length && <p className="empty">No orders are awaiting approval.</p>}</section> : <section className="order-list"><div className="list-heading"><h2>Transaction history</h2><span>{manualHistory.length}</span></div>{manualHistory.map((order) => <button className="order-row" key={order.id} onClick={() => void openManualOrder(order.id)}><div><strong>{order.customerName || "Customer"}</strong><span>{order.shopifyOrderName || order.productDisplayName}</span><small>{order.paymentApprovedAt ? `Approved ${date(order.paymentApprovedAt)}` : date(order.createdAt)}</small></div><div><span className="status status-packed">{manualStatus(order)}</span><b>›</b></div></button>)}{!manualHistory.length && !busy && <p className="empty">No transaction history yet.</p>}</section>}{notice && <p className="error">{notice}</p>}</main>;
  if (workspace === "reports") return <main><header className="topbar"><div>{picker}<p className="eyebrow">REPORTING</p><h1>Sales report</h1><p>{salesReport?.savedAt ? `Last updated ${new Date(salesReport.savedAt).toLocaleTimeString("en-MY", { hour: "2-digit", minute: "2-digit" })}` : "Preparing your first report…"}</p></div><button className="avatar" onClick={signOut}>{session.displayName.slice(0, 1).toUpperCase()}</button></header><section className="card mobile-filters"><div className="filter-heading"><h2>Report filters</h2><button className="quiet" onClick={() => { setSourceFilter("all"); setFromDate(""); setToDate(""); void loadSalesReport(); }}>Clear</button></div><div className="filter-grid"><label>From<input type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /></label><label>To<input type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} /></label><label>Source<select value={sourceFilter} onChange={(event) => setSourceFilter(event.target.value as SourceFilter)}><option value="all">All sources</option><option value="shopify">Shopify</option><option value="tiktok">TikTok Shop</option></select></label></div></section><section className="card mobile-report"><div className="filter-heading"><div><h2>Sales reporting</h2><p>{salesReport ? `${salesReport.orderCount} sales in this range` : "Calculating in the background…"}</p></div><button className="quiet" disabled={reportLoading} onClick={() => void loadSalesReport()}>{reportLoading ? "Refreshing…" : "Refresh"}</button></div>{salesReport && <><div className="report-channel"><span>Shopify <b>{salesReport.channel.shopify.count} sales</b><strong>{money.format(salesReport.channel.shopify.sales)}</strong></span><span>TikTok Shop <b>{salesReport.channel.tiktok.count} sales</b><strong>{money.format(salesReport.channel.tiktok.sales)}</strong></span></div><div className="report-metrics"><span>Total sales<strong>{money.format(salesReport.sales.gross)}</strong></span><span>Collected<strong>{money.format(salesReport.sales.totalCollected)}</strong></span><span>Discounts<strong>{money.format(salesReport.sales.productDiscounted + salesReport.sales.shippingDiscounted)}</strong></span><span>Fees<strong>{money.format(salesReport.sales.totalFees)}</strong></span><span>Cash after fees<strong>{money.format(salesReport.sales.collected)}</strong></span></div></>}<p>{reportLoading ? "Your saved report remains visible while the latest figures are calculated." : "Reporting is refreshed only in this workspace, so opening Orders stays fast."}</p></section>{notice && <p className="error">{notice}</p>}</main>;
  return <main><style>{`.mobile-report{display:none}`}</style>
    <div className={`pull-to-refresh ${pullDistance ? "visible" : ""}`} style={{ height: pullDistance }} aria-hidden="true">{pullDistance >= 56 ? "Release to refresh" : "Pull down to refresh"}</div>
    <header className="topbar"><div>{picker}<p className="eyebrow">FULFILMENT</p><h1>Orders</h1><p>{dashboard.orders.length} of {dashboard.totalCount || "…"} orders loaded</p></div><button className="avatar" onClick={signOut}>{session.displayName.slice(0, 1).toUpperCase()}</button></header>
    {updatesAvailable && <button className="updates-banner" onClick={() => void refresh(true)} disabled={busy}><span>New orders or changes are ready.</span><strong>{busy ? "Refreshing…" : "Refresh now"}</strong></button>}
    <section className="card mobile-filters"><div className="filter-heading"><h2>Filters</h2><button className="quiet" onClick={() => { setStatusFilter("all"); setSourceFilter("all"); setFromDate(""); setToDate(""); }}>Clear</button></div><div className="filter-grid"><label>From<input type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /></label><label>To<input type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} /></label><label>Source<select value={sourceFilter} onChange={(event) => setSourceFilter(event.target.value as SourceFilter)}><option value="all">All sources</option><option value="shopify">Shopify</option><option value="tiktok">TikTok Shop</option></select></label><label>Status<select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="all">All statuses</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div></section>
    {session.role === "admin" && <section className="card mobile-report"><div className="filter-heading"><div><h2>Sales reporting</h2><p>{salesReport ? `${salesReport.orderCount} sales in this range` : "Loading reporting…"}</p></div><button className="quiet" disabled={reportLoading} onClick={() => void loadSalesReport()}>{reportLoading ? "Loading…" : "Refresh"}</button></div>{salesReport && <><div className="report-channel"><span>Shopify <b>{salesReport.channel.shopify.count} sales</b><strong>{money.format(salesReport.channel.shopify.sales)}</strong></span><span>TikTok Shop <b>{salesReport.channel.tiktok.count} sales</b><strong>{money.format(salesReport.channel.tiktok.sales)}</strong></span></div><div className="report-metrics"><span>Total sales<strong>{money.format(salesReport.sales.gross)}</strong></span><span>Collected<strong>{money.format(salesReport.sales.totalCollected)}</strong></span><span>Discounts<strong>{money.format(salesReport.sales.productDiscounted + salesReport.sales.shippingDiscounted)}</strong></span><span>Fees<strong>{money.format(salesReport.sales.totalFees)}</strong></span><span>Cash after fees<strong>{money.format(salesReport.sales.collected)}</strong></span></div></>}</section>}
    <div className="metrics"><article><span>New</span><strong>{dashboard.counts.new_order || 0}</strong></article><article><span>In production</span><strong>{dashboard.counts.sent_for_sewing || 0}</strong></article><article><span>Packed</span><strong>{dashboard.counts.packed || 0}</strong></article></div>
    <div className="toolbar"><button className="scan" onClick={scan} disabled={busy}>Scan order</button><button className="quiet refresh" onClick={() => void refresh(true)} disabled={busy}>{busy ? "Refreshing…" : "Refresh"}</button></div>
    <form className="search" onSubmit={(event) => { event.preventDefault(); void lookup(new FormData(event.currentTarget).get("code") as string); }}><input name="code" placeholder="Search order number" /><button disabled={busy}>Search</button></form>
    <section className="order-list"><div className="list-heading"><h2>All orders</h2><span>{dashboard.totalCount}</span></div>{dashboard.orders.map((order) => <button className="order-row" key={order.id} onClick={() => void openOrder(order.id)}><div><strong>#{order.orderNumber}</strong><span>{order.customerName || "Customer"} · {order.plushName || order.product || "Plushie"}</span><small>{date(order.orderDate)}</small></div><div><span className={`status status-${order.status}`}>{labels[order.status] || order.status}</span><b>›</b></div></button>)}{!dashboard.orders.length && <p className="empty">No saved orders yet. Pull down or tap Refresh while connected.</p>}{dashboard.hasMore && <button className="load-more" onClick={() => void loadMore()} disabled={loadingMore}>{loadingMore ? "Loading orders…" : "Load next 100 orders"}</button>}</section>
    {opening && <div className="loading">Opening order…</div>}{notice && <p className="error">{notice}</p>}
  </main>;
}

createRoot(document.getElementById("root")!).render(<App />);
