import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { CapacitorBarcodeScanner, CapacitorBarcodeScannerTypeHint } from "@capacitor/barcode-scanner";
import "./style.css";

const API = "https://meaningful-plushies-fulfilment.vercel.app/api/mobile";
type Session = { token: string; username: string; displayName: string; role: "admin" | "staff" };
type Order = { id: string; orderNumber: string; customerName: string; plushName: string; status: string; character: string };
const labels: Record<string, string> = { awaiting_customisation: "Awaiting customisation", new_order: "New order", uploading_audio: "Uploading audio", sent_for_sewing: "Sent for sewing", packed: "Packed", shipped: "Shipped", issue: "Issue" };
const next: Record<string, string> = { awaiting_customisation: "new_order", new_order: "uploading_audio", uploading_audio: "sent_for_sewing", sent_for_sewing: "packed", packed: "shipped" };

function App() {
  const [session, setSession] = useState<Session | null>(null); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [order, setOrder] = useState<Order | null>(null); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  async function login(e: React.FormEvent) { e.preventDefault(); setBusy(true); try { const r = await fetch(`${API}/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username, password }) }); const data = await r.json(); if (!r.ok) throw Error(data.error); setSession(data); setPassword(""); } catch (e) { setNotice(e instanceof Error ? e.message : "Unable to sign in."); } finally { setBusy(false); } }
  async function lookup(code: string) { if (!session || !code) return; setBusy(true); try { const r = await fetch(`${API}/orders/lookup?code=${encodeURIComponent(code)}`, { headers: { authorization: `Bearer ${session.token}` } }); const data = await r.json(); if (!r.ok) throw Error(data.error); if (!data.order) throw Error("No order matches this code."); setOrder(data.order); setNotice(""); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not find this order."); } finally { setBusy(false); } }
  async function scan() { try { const result = await CapacitorBarcodeScanner.scanBarcode({ hint: CapacitorBarcodeScannerTypeHint.ALL, scanInstructions: "Scan the order barcode or QR code" }); if (result.ScanResult) await lookup(result.ScanResult); } catch { setNotice("The camera scanner could not start. You can enter the code manually."); } }
  async function advance() { if (!session || !order || !next[order.status]) return; setBusy(true); try { const r = await fetch(`${API}/orders/transition`, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${session.token}` }, body: JSON.stringify({ orderId: order.id, fromStatus: order.status, toStatus: next[order.status] }) }); const data = await r.json(); if (!r.ok) throw Error(data.error === "ORDER_CHANGED" ? "This order was updated on another device. Scan it again." : data.error); setOrder(data.order); setNotice("Stage updated."); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not update the order."); } finally { setBusy(false); } }
  if (!session) return <main><h1>Meaningful<br/>Fulfilment</h1><p>Warehouse sign in</p><form onSubmit={login}><input value={username} onChange={e => setUsername(e.target.value)} placeholder="Username" autoComplete="username"/><input value={password} onChange={e => setPassword(e.target.value)} placeholder="Password" type="password" autoComplete="current-password"/><button disabled={busy}>{busy ? "Signing in…" : "Sign in"}</button></form>{notice && <small>{notice}</small>}</main>;
  return <main><header><div><h1>Meaningful Fulfilment</h1><p>{session.displayName} · Warehouse</p></div><button className="quiet" onClick={() => { setSession(null); setOrder(null); }}>Sign out</button></header><button className="scan" onClick={scan} disabled={busy}>Scan barcode / QR</button><form className="manual" onSubmit={e => { e.preventDefault(); lookup(new FormData(e.currentTarget).get("code") as string); }}><input name="code" placeholder="Enter order code"/><button disabled={busy}>Find</button></form>{notice && <small>{notice}</small>}{order && <section><p className="eyebrow">ORDER #{order.orderNumber}</p><h2>{order.plushName || "Meaningful Plushie"}</h2><dl><dt>Customer</dt><dd>{order.customerName || "—"}</dd><dt>Character</dt><dd>{order.character || "—"}</dd><dt>Current stage</dt><dd>{labels[order.status] || order.status}</dd></dl>{next[order.status] ? <button onClick={advance} disabled={busy}>{busy ? "Updating…" : `Move to ${labels[next[order.status]]}`}</button> : <p>This order is complete.</p>}</section>}</main>;
}
createRoot(document.getElementById("root")!).render(<App />);
