import type { Order } from "./types";

const now = new Date().toISOString();

export const demoOrders: Order[] = [
  {
    id: "1359",
    orderNumber: "1359",
    orderDate: "2026-06-04T08:47:52+08:00",
    customerName: "Zaidee Tahir",
    phone: "601112392356",
    email: "zaidee@example.com",
    address: "Ampang, Kuala Lumpur",
    product: "Build Your Meaningful Plushie",
    character: "Hunnie",
    setIndicator: "Set 1 of 1",
    idWebsiteLink: "https://example.com/order/1359",
    voiceLength: 20,
    plushName: "Baby Amoylicious",
    certificateCode: "13594072239",
    meaningfulNote: "A loving reminder to keep close.",
    meaningfulMessage: "https://example.com/message-1359",
    remark: "Handle with care",
    voiceUploadStatus: "received",
    courier: "",
    trackingNumber: "",
    status: "awaiting_voice",
    internalNotes: "",
    statusHistory: [{ id: "1359-1", status: "awaiting_voice", changedAt: now, changedBy: "Admin" }],
    importedAt: now,
    updatedAt: now,
  },
  {
    id: "1360",
    orderNumber: "1360",
    orderDate: "2026-06-04T11:57:23+08:00",
    customerName: "Aliya Ali",
    phone: "0128186699",
    email: "aliya@example.com",
    address: "Rawang, Selangor",
    product: "Build Your Meaningful Plushie",
    character: "Billy",
    setIndicator: "Set 1 of 1",
    idWebsiteLink: "https://example.com/order/1360",
    voiceLength: 20,
    plushName: "ROHI",
    certificateCode: "13605443839",
    meaningfulNote: "I will always be here with you.",
    meaningfulMessage: "https://example.com/message-1360",
    remark: "",
    voiceUploadStatus: "checked",
    courier: "J&T Express",
    trackingNumber: "",
    status: "ready_to_make",
    internalNotes: "Voice checked and ready for production.",
    statusHistory: [
      { id: "1360-1", status: "awaiting_voice", changedAt: now, changedBy: "Admin" },
      { id: "1360-2", status: "ready_to_make", changedAt: now, changedBy: "Aina" },
    ],
    importedAt: now,
    updatedAt: now,
  },
  {
    id: "1361",
    orderNumber: "1361",
    orderDate: "2026-06-05T09:12:17+08:00",
    customerName: "Emily Cheng",
    phone: "0128073322",
    email: "emily@example.com",
    address: "Subang Jaya, Selangor",
    product: "Build Your Meaningful Plushie",
    character: "Dragon Warrior",
    setIndicator: "Set 1 of 1",
    idWebsiteLink: "https://example.com/order/1361",
    voiceLength: 5,
    plushName: "Sumo",
    certificateCode: "13611937415",
    meaningfulNote: "Happy Father's Day!",
    meaningfulMessage: "https://example.com/message-1361",
    remark: "Packing photo required",
    voiceUploadStatus: "checked",
    courier: "J&T Express",
    trackingNumber: "MY1234567890",
    status: "packed",
    internalNotes: "Packing photo required before fulfilment.",
    statusHistory: [
      { id: "1361-1", status: "new_order", changedAt: now, changedBy: "Admin" },
      { id: "1361-2", status: "packed", changedAt: now, changedBy: "Farah" },
    ],
    importedAt: now,
    updatedAt: now,
  },
  {
    id: "1357",
    orderNumber: "1357",
    orderDate: "2026-06-03T15:30:00+08:00",
    customerName: "Nur Hidayah",
    phone: "0175551122",
    email: "hidayah@example.com",
    address: "Shah Alam, Selangor",
    product: "Build Your Meaningful Plushie",
    character: "Tootsie",
    setIndicator: "Set 1 of 1",
    idWebsiteLink: "https://example.com/order/1357",
    voiceLength: 10,
    plushName: "Bubu",
    certificateCode: "13578821440",
    meaningfulNote: "Thank you for always being there.",
    meaningfulMessage: "https://example.com/message-1357",
    remark: "",
    voiceUploadStatus: "checked",
    courier: "Ninja Van",
    trackingNumber: "NV77881230",
    status: "fulfilled",
    internalNotes: "",
    statusHistory: [{ id: "1357-1", status: "fulfilled", changedAt: now, changedBy: "Admin" }],
    importedAt: now,
    updatedAt: now,
  },
];
