import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { createManualOrderDiscounts } from "@/lib/manual-orders";
import { saveManualOrder, supabase } from "@/lib/supabase";

const db = () => { if (!supabase) throw new Error("Supabase is not configured."); return supabase; };
export async function GET() { try { const { data, error } = await db().from("preorders").select("*").order("created_at", { ascending: false }); if (error) throw error; return NextResponse.json({ ok: true, preorders: data || [] }); } catch (e) { return NextResponse.json({ ok: false, error: e instanceof Error ? e.message : "Could not load preorders." }, { status: 500 }); } }
export async function POST(request: Request) { try { const b = await request.json(); const total = Number(b.totalAmount), deposit = Number(b.depositAmount); if (!b.customerName || !b.phone || !b.productKey || !Number.isFinite(total) || total <= 0 || !Number.isFinite(deposit) || deposit < 0 || deposit > total) throw new Error("Enter a valid customer, normal order price, and deposit."); const { data, error } = await db().from("preorders").insert({ id: randomUUID(), customer_name: b.customerName, phone: b.phone, character: b.character, product_key: b.productKey, shipping_region: b.shippingRegion === "EAST" ? "EAST" : "WEST", total_amount: total, deposit_amount: deposit, balance_due_date: b.balanceDueDate || null, payment_receipts: b.paymentReceipts || [] }).select("*").single(); if (error) throw error; return NextResponse.json({ ok: true, preorder: data }); } catch (e) { return NextResponse.json({ ok: false, error: e instanceof Error ? e.message : "Could not create preorder." }, { status: 400 }); } }
export async function PATCH(request: Request) { try { const { preorder } = await request.json(); if (!preorder) throw new Error("Choose a preorder."); const manualOrder = await createManualOrderDiscounts({ customerName: preorder.customer_name, phone: preorder.phone, character: preorder.character, productKey: preorder.product_key, shippingRegion: preorder.shipping_region }); await saveManualOrder({ ...manualOrder, paymentReceipts: preorder.payment_receipts || [] }); const { error } = await db().from("preorders").update({ status: "paid", manual_order_id: manualOrder.id, paid_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", preorder.id); if (error) throw error; return NextResponse.json({ ok: true, manualOrder }); } catch (e) { return NextResponse.json({ ok: false, error: e instanceof Error ? e.message : "Could not mark preorder paid." }, { status: 400 }); } }
