"use client";

import { FormEvent, useEffect, useState } from "react";

type Preorder = { id: string; customer_name: string; phone: string; character: string; product_key: string; shipping_region: "WEST" | "EAST"; total_amount: number; deposit_amount: number; balance_due_date: string | null; status: string; payment_receipts: Array<{ fileName: string; url: string }>; manual_order_id: string | null };
const products = ["billy-5", "billy-10", "billy-20", "tootsie-5", "tootsie-10", "tootsie-20", "hunnie-5", "hunnie-10", "hunnie-20", "dragon-warrior-5", "dragon-warrior-10", "dragon-warrior-20"];

export default function PreordersPage() {
  const [items, setItems] = useState<Preorder[]>([]); const [files, setFiles] = useState<File[]>([]); const [notice, setNotice] = useState("");
  const [form, setForm] = useState({ customerName: "", phone: "", character: "Billy", productKey: "billy-5", shippingRegion: "WEST", totalAmount: "", depositAmount: "", balanceDueDate: "" });
  const balance = Math.max(0, Number(form.totalAmount || 0) - Number(form.depositAmount || 0));
  const load = async () => { const result = await fetch("/api/preorders").then((r) => r.json()); if (result.ok) setItems(result.preorders); else setNotice(result.error); };
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); try { const receipts = []; for (const file of files) { const data = new FormData(); data.append("file", file); const upload = await fetch("/api/crm/media-assets", { method: "POST", body: data }).then((r) => r.json()); if (!upload.ok) throw new Error(upload.error); receipts.push({ fileName: file.name, url: upload.asset.originalUrl }); } const result = await fetch("/api/preorders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, paymentReceipts: receipts }) }).then((r) => r.json()); if (!result.ok) throw new Error(result.error); setFiles([]); setForm((current) => ({ ...current, customerName: "", phone: "", depositAmount: "", balanceDueDate: "" })); setNotice("Pre-order saved."); await load(); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not save pre-order."); } }
  async function markPaid(preorder: Preorder) { try { const result = await fetch("/api/preorders", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "mark_paid", preorder }) }).then((r) => r.json()); if (!result.ok) throw new Error(result.error); setNotice("Paid — Manual Order link created."); await load(); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not mark paid."); } }
  return <main style={{ maxWidth: 1100, margin: "32px auto", fontFamily: "Arial, sans-serif" }}><h1>Pre-orders</h1><p>Record deposits, payment proof, and the date the balance is due. Once fully paid, create the Manual Order checkout link.</p>{notice && <p>{notice}</p>}<form onSubmit={submit} style={{ display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 12, border: "1px solid #d7e0ee", padding: 20, borderRadius: 12 }}><input required placeholder="Customer name" value={form.customerName} onChange={(e) => setForm({ ...form, customerName: e.target.value })}/><input required placeholder="Phone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })}/><input required placeholder="Character" value={form.character} onChange={(e) => setForm({ ...form, character: e.target.value })}/><select value={form.productKey} onChange={(e) => setForm({ ...form, productKey: e.target.value })}>{products.map((product) => <option key={product}>{product}</option>)}</select><input required type="number" min="0" step="0.01" placeholder="Normal order price (RM)" value={form.totalAmount} onChange={(e) => setForm({ ...form, totalAmount: e.target.value })}/><input required type="number" min="0" step="0.01" placeholder="Deposit received (RM)" value={form.depositAmount} onChange={(e) => setForm({ ...form, depositAmount: e.target.value })}/><strong>Balance: RM {balance.toFixed(2)}</strong><label>Balance payment date<input type="date" value={form.balanceDueDate} onChange={(e) => setForm({ ...form, balanceDueDate: e.target.value })}/></label><label>Payment receipts (PDF / images, multiple)<input type="file" multiple accept="application/pdf,image/png,image/jpeg,image/webp" onChange={(e) => setFiles(Array.from(e.target.files || []))}/></label><span>{files.map((file) => file.name).join(", ")}</span><button type="submit">Save pre-order</button></form><h2>Saved pre-orders</h2><table width="100%"><thead><tr><th>Customer</th><th>Deposit</th><th>Balance</th><th>Due</th><th>Receipts</th><th>Status</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.customer_name}<br/>{item.phone}</td><td>RM {Number(item.deposit_amount).toFixed(2)}</td><td>RM {(Number(item.total_amount) - Number(item.deposit_amount)).toFixed(2)}</td><td>{item.balance_due_date || "-"}</td><td>{item.payment_receipts?.map((receipt) => <a key={receipt.url} href={receipt.url} target="_blank">{receipt.fileName} </a>)}</td><td>{item.status}</td><td>{item.status === "deposit_paid" && <button onClick={() => void markPaid(item)}>Mark balance paid & create Manual Order</button>}</td></tr>)}</tbody></table></main>;
}
